name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile main.py ^
          --add-data "module.py;." ^
          --add-data ".env;." ^
          --add-data "Images;Images"

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: MoodTunes-EXE
        path: dist/main.exe
